services:

  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 5672:5672
    env_file:
      - ../defaults/rabbitmq_server.env

  influxdb:
    image: influxdb:2.0
    container_name: influxdb
    hostname: influxdb
    ports:
      - 8086:8086
    env_file:
      - ../defaults/influxdb_server.env

  file_multisensor:
    image: "chronis10/teaching-sensors:${ARCH:-amd64}"
    container_name: file_multisensor
    depends_on:
      - rabbitmq
    restart: on-failure
    environment:
      - SERVICE_TYPE=file.csv_feed.CSVFeed
      - SERVICE_NAME=file_multisensor
      - FILE_PATH=./raw_data/carla/multisensor_carla.csv 
      - TRANSMIT_RATE=0.1
      - OUTPUT_TOPIC=sensor.carla.value
    env_file:
      - ../defaults/rabbitmq_client.env
    volumes:
      - ../raw_data:/app/raw_data

  rl_predictor:
    image: "chronis10/teaching-ai-toolkit:${ARCH:-amd64}"
    container_name: ai_toolkit
    depends_on: 
      - rabbitmq
    restart: on-failure
    environment:
      - SERVICE_TYPE=modules.rl_module.RLModule
      - SERVICE_NAME=rl_module
      - TOPICS=sensor.*.value
      - MODEL_PATH=/app/storage/RL_model_episode_470_77.6718928615904.h5
    env_file:
      - ../defaults/rabbitmq_client.env
    volumes:
      - ../data_storage/RL:/app/storage

  influxdb_logger:
    image: "chronis10/teaching-data:${ARCH:-amd64}"
    container_name: influxdb_logger
    depends_on:
      - rabbitmq
      - influxdb
    restart: on-failure
    environment:
      - SERVICE_TYPE=influxdb.client.InfluxDBClientHandler
      - SERVICE_NAME=influxdb_logger
      - TOPICS=*.*.value
    env_file:
      - ../defaults/rabbitmq_client.env
      - ../defaults/influxdb_client.env