services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    env_file:
      - ../defaults/rabbitmq_server.env

  influxdb:
    image: influxdb:2.0
    container_name: influxdb
    hostname: influxdb
    ports:
      - 8086:8086
    env_file:
      - ../defaults/influxdb_server.env

  file_multisensor:
    image: "chronis10/teaching-sensors:${ARCH:-amd64}"
    container_name: file_multisensor
    depends_on:
      - rabbitmq
    restart: on-failure
    environment:
      - SERVICE_TYPE=file.csv_feed.CSVFeed
      - SERVICE_NAME=file_multisensor
      - FILE_PATH=./raw_data/carla/multisensor_carla.csv 
      - TRANSMIT_RATE=0.1
      - OUTPUT_TOPIC=sensor.carla.value
    env_file:
      - ../defaults/rabbitmq_client.env
    volumes:
      - ../raw_data:/app/raw_data

  rl_predictor_federated:
    image: "chronis10/teaching-ai-toolkit:${ARCH:-amd64}"
    container_name: ai_toolkit
    depends_on: 
      - rabbitmq
    restart: on-failure
    environment:
      - SERVICE_TYPE=modules.rl_module_federated.RLModule
      - SERVICE_NAME=rl_module_federated
      - PREDICTIONS_TOPIC=prediction.driving_profile.value
      - TOPICS=*.*.value
      - INITIAL_MODEL_PATH=/app/storage/RL/RL_model_episode_470_77.6718928615904.h5
      - LOCAL_MODELS_PATH=/app/storage/federated/local
      - FEDERATED_MODELs_PATH=/app/storage/federated/cloud
      - NEW_MODEL_INTERVAL=10
      - FEDERATED_MODEL_TOPIC=itml.federated_model.value
      - LOCAL_MODEL_TOPIC=rlmodel.new_model.value
      
    env_file:
      - ../defaults/rabbitmq_client.env
    volumes:
      - ../data_storage:/app/storage
      - ../../teaching-ai-toolkit/modules:/app/modules



  influxdb_logger:
    image: "chronis10/teaching-data:${ARCH:-amd64}"
    container_name: influxdb_logger
    depends_on:
      - rabbitmq
      - influxdb
    restart: on-failure
    environment:
      - SERVICE_TYPE=influxdb.client.InfluxDBClientHandler
      - SERVICE_NAME=influxdb_logger
      - TOPICS=*.*.value
    env_file:
      - ../defaults/rabbitmq_client.env
      - ../defaults/influxdb_client.env