FROM teaching_image
WORKDIR /app
COPY $PWD/modules/ai_modules/RL_predictor/module.py module.py
COPY $PWD/modules/ai_modules/RL_predictor/requirements.txt module_requirements.txt
COPY $PWD/modules/ai_modules/RL_predictor/requirements.txt module_requirements.txt
COPY tools tools
RUN pip install -r module_requirements.txt
RUN pip install -r tools/requirements.txt
COPY $PWD/modules/core_modules/process_module/main.py main.py
CMD ["python3", "main.py"]