services:
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 5672:5672
    env_file:
      - ./env_files/rabbitmq_server.env

  influxdb:
    image: influxdb:2.0
    container_name: influxdb
    hostname: influxdb
    ports:
      - 8086:8086
    env_file:
      - ./env_files/influxdb_server.env
  
  file_multisensor:
    build:
      context: .
      dockerfile: Dockerfile.file_sensors
    image: file_multisensor
    container_name: file_multisensor
    depends_on: 
      - rabbitmq
    restart: on-failure
    environment:
      - SERVICE_NAME=file_sensor
      - RABBIT_HOST=rabbitmq
      - FILE_SOURCE=data_storage/raw_data/carla/multisensor_carla.csv 
      - TRANSMIT_RATE=0.1
    env_file:
      - ./env_files/rabbitmq_client.env
    volumes:
      - ./data_storage:/app/data_storage

  influxdb_logger:
    build:
      context: .
      dockerfile: Dockerfile.influxdb_logger
    container_name: influxdb_logger
    depends_on: 
      - rabbitmq
      - influxdb
    restart: on-failure
    environment:
      - SERVICE_NAME=influxdb_logger
      - INPUT_TOPIC=stress,excitement,ay,gz,speed,speed_limit
      - RABBIT_HOST=rabbitmq
      - INFLUXDB_HOST=influxdb
    env_file:
      - ./env_files/rabbitmq_client.env
      - ./env_files/influxdb_client.env