version: '3'

services:

  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 5672:5672
    env_file:
      - env/comm/rabbitmq_server.env

  rpi_camera:
    image: "chronis10/teaching-sensors:${ARCH:-amd64}"
    container_name: rpi_camera
    depends_on: 
      - rabbitmq
    restart: on-failure
    env_file:
      - env/rpi_camera.env
      - env/comm/rabbitmq_client.env

  stress_module:
    image: "chronis10/teaching-ai-toolkit:${ARCH:-amd64}"
    container_name: stress_module
    depends_on: 
      - rabbitmq
    restart: on-failure
    env_file:
      - env/stress_module.env
      - env/comm/rabbitmq_client.env
    volumes:
      - $APP_DIR/data_storage:/app/storage
