services:
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 5672:5672
    env_file:
      - ./env_files/rabbitmq_server.env

  influxdb:
    image: influxdb:2.0
    container_name: influxdb
    hostname: influxdb
    ports:
      - 8086:8086
    env_file:
      - ./env_files/influxdb_server.env
  
  shimmer_sensors:
    build:
      context: .
      dockerfile: Dockerfile.shimmer_device
    image: shimmer_sensors
    container_name: shimmer_sensors
    depends_on: 
      - rabbitmq
    restart: on-failure
    environment:
      - SERVICE_NAME=file_sensor
      - RABBIT_HOST=rabbitmq
      - SAMPLING_RATE=64
      - DEVICE_PORT=/dev/ttyUSB0
    env_file:
      - ./env_files/rabbitmq_client.env
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0

  influxdb_logger:
    build:
      context: .
      dockerfile: Dockerfile.influxdb_logger
    container_name: influxdb_logger
    depends_on: 
      - rabbitmq
      - influxdb
    restart: on-failure
    environment:
      - SERVICE_NAME=influxdb_logger
      - INPUT_TOPIC=HR,EDA
      - RABBIT_HOST=rabbitmq
      - INFLUXDB_HOST=influxdb
    env_file:
      - ./env_files/rabbitmq_client.env
      - ./env_files/influxdb_client.env