services:

  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    env_file:
      - env/comm/rabbitmq_server.env

  influxdb:
    image: influxdb:2.0
    container_name: influxdb
    hostname: influxdb
    ports:
      - 8086:8086
    env_file:
      - env/comm/influxdb_server.env

  shimmer_sensors:
    image: "chronis10/teaching-sensors:${ARCH:-amd64}"
    container_name: shimmer_sensors
    depends_on:
      - rabbitmq
      - influxdb
    restart: on-failure
    env_file:
      - env/shimmer_sensors.env
      - env/comm/rabbitmq_client.env
    devices:
      - /dev/rfcomm0:/dev/ttyS0

  influxdb_logger:
    image: "chronis10/teaching-data:${ARCH:-amd64}"
    container_name: influxdb_logger
    depends_on:
      - rabbitmq
      - influxdb
    restart: on-failure
    env_file:
      - env/influxdb_logger.env
      - env/comm/rabbitmq_client.env
      - env/comm/influxdb_client.env